// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ZyhctK903BAedoQKfeTty7d7Mf70pyE',
    appId: '1:827004052015:web:3fb97135c5b5994d365cda',
    messagingSenderId: '827004052015',
    projectId: 'infound',
    authDomain: 'infound.firebaseapp.com',
    storageBucket: 'infound.firebasestorage.app',
    databaseURL: "https://infound-default-rtdb.asia-southeast1.firebasedatabase.app",
    measurementId: 'G-RV8TGK0D72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsEn-68wfXky4DYRHb6iUxogupzNmW71Y',
    appId: '1:827004052015:android:6d99bd08ec5a1b22365cda',
    messagingSenderId: '827004052015',
    projectId: 'infound',
    storageBucket: 'infound.firebasestorage.app',
    databaseURL: "https://infound-default-rtdb.asia-southeast1.firebasedatabase.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4F_VhFEp_fyhzz7idcnjEUQ5EjdYbCRE',
    appId: '1:827004052015:ios:24e28492f18c66a9365cda',
    messagingSenderId: '827004052015',
    projectId: 'infound',
    storageBucket: 'infound.firebasestorage.app',
    iosBundleId: 'com.infound.infound',
    databaseURL: "https://infound-default-rtdb.asia-southeast1.firebasedatabase.app",
  );
}
